[package]
name = "rdbc-postgres"
description = " Postgres RDBC Driver"
version = "0.1.6"
authors = ["Andy Grove <andygrove73@gmail.com>"]
license = "Apache-2.0"

edition = "2018"

[dependencies]
rdbc = { path = "../rdbc", features = ["sync"] }
sqlparser = "0.6.1"
r2d2_postgres = "0.16.0"
